[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd templates && npm install"
]

[phases.build]
cmds = [
  "cd templates && npm run build"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
